testing

diff --git a/.github/workflows/publish-npm.yml b/.github/workflows/publish-npm.yml
--- a/.github/workflows/publish-npm.yml
+++ b/.github/workflows/publish-npm.yml
@@ -51,10 +51,10 @@ jobs:
         # Fail if package name not properly configured
         run: exit 1
 
-      - name: Check if package version matches with tag
-        if: github.ref != steps.get_package_info.outputs.PACKAGE_VERSION
-        # Fail if package version not properly setted
-        run: exit 1
+      # - name: Check if package version matches with tag
+      #   if: github.ref != steps.get_package_info.outputs.PACKAGE_VERSION
+      #   # Fail if package version not properly setted
+      #   run: exit 1
       
       - name: Check if package repository matches with repository
         if: github.repositoryUrl != steps.get_package_info.outputs.PACKAGE_REPOSITORY
